### ISSUE TITLE
启动iredapd报错

### ISSUE THREAD

**Issue by saltswater** [iredmail/iRedAPD#10]
from web import sqlquote
utils.py文件里有“from web import sqlquote”，提示“No module named 'web'”

**Comment by saltswater** [comment]
i can't to find the web module in python. 
where can i find the module file? thanks~

**Comment by saltswater** [comment]
I can't find the web module file.
Where can i find it?
Thank you~

**Comment by iredmail** [comment]
- 你是如何安装 iRedAPD 的？
- 手工安装 web.py 模块后重启 iredapd 服务试试：`pip3 install web.py>=0.6.2`

**Comment by saltswater** [comment]
谢谢~
