### ISSUE TITLE
iRedAPD logrotate script generates Cron error messages

### ISSUE THREAD

**Issue by clickbg** [iredmail/iRedAPD#17]
Hi,

This is a very minor bug which unfortunately generates tickets from our systems since we monitor every cron output.
Basically in https://github.com/iredmail/iRedAPD/blob/114f99384369e28933b64216584a7b9ba6f951e9/samples/logrotate.d/iredapd#L10-L12

Generates output:

```
/etc/cron.daily/logrotate:

Redirecting to /bin/systemctl restart rsyslog.service
```

Which causes our systems to log an incident since it`s not expected that a cronjob would generate unhanded messages in the error output.

Could you please change it to something like this, taken from the rsyslog logrotate job:

```
    postrotate
        /usr/bin/systemctl -s HUP kill rsyslog.service >/dev/null 2>&1 || true
    endscript
```

Since currently we have to apply this fix after every iRedAPD upgrade.

Thank you for the amazing software!

**Comment by iredmail** [comment]
Would you like to send a pull request? :)

**Comment by clickbg** [comment]
Sure, sorry for not starting with this. I have created https://github.com/iredmail/iRedAPD/pull/18 

Thanks!
