### ISSUE TITLE
Unable to send notifications using sendmail command

### ISSUE THREAD

**Issue by StnVsl** [iredmail/iRedAPD#21]
The sendmail_with_cmd function fails with a TypeError: a bytes-like object is required, not 'str'

**Comment by iredmail** [comment]
- Which Linux distribution and release are you running?
- Which iRedAPD release are you running?

**Comment by StnVsl** [comment]
1.7.1 OPENLDAP edition on Debian 12.
iRedAPD-5.6.0

**Comment by iredmail** [comment]
Hi @StnVsl,

v5.8.1 has been released with this fix. Please upgrade and let me know whether it works for you or not.

**Comment by StnVsl** [comment]
The issue has been fixed. Thank you.
