### ISSUE TITLE
Can't list blacklist with wblist in 4.4 + 1 commit

### ISSUE THREAD

**Issue by olivier-lz** [iredmail/iRedAPD#4]
Hi,

~~I juste want to upgrade iRedApd-4.4 to use `wblist.py`, but when I download the last package from https://github.com/iredmail/iRedAPD/releases/4.4.tar.gz or the ZIP file ; **none of them include the change** in the commit https://github.com/iredmail/iRedAPD/compare/4.4...master.~~

~~To be sure I apply manually the commit, and **now** I can add into blacklist `/usr/bin/python /opt/iRedAPD-4.4/tools/wblist_admin.py --add --blacklist @example.com`.~~

In the lastes devloppement (4.4 + 1 commit) I continue to see some `.decode()`, and for example, I can't list BL : 
```bash
# /usr/bin/python /opt/iRedAPD-4.4/tools/wblist_admin.py --list --blacklist
* Establishing SQL connection.
* List all inbound blacklist for account: @.
AttributeError("'buffer' object has no attribute 'decode'",)
```

I'm available for testing if you need.

--
_Thanks for all your work._

**Comment by iredmail** [comment]
I don't have such issue with MariaDB. Are you running PGSQL? I will test it immediately.

**Comment by iredmail** [comment]
Btw, could you please run the command with `python3` instead of `python`? It seems your `python` command is Python 2.

**Comment by iredmail** [comment]
Fixed one more issue, you can try the latest development edition and run with Python 3 (not `python` or `python2`, but `python3`).

**Comment by olivier-lz** [comment]
Hi.

Thanks for your consideration, and quick response.

1. Yes I use PGSQL.

2. `/usr/bin/python` is actually python2, not python3, like you recommand, but another error occurs.
```bash
root@odin:~# /usr/bin/python /opt/iRedAPD-4.4/tools/wblist_admin.py --list --blacklist
* Establishing SQL connection.
* List all inbound blacklist for account: @.
AttributeError("'buffer' object has no attribute 'decode'",)

root@odin:~# /usr/bin/python2 /opt/iRedAPD-4.4/tools/wblist_admin.py --list --blacklist
* Establishing SQL connection.
* List all inbound blacklist for account: @.
AttributeError("'buffer' object has no attribute 'decode'",)

root@odin:~# /usr/bin/python3 /opt/iRedAPD-4.4/tools/wblist_admin.py --list --blacklist
* Establishing SQL connection.
* List all inbound blacklist for account: @.
TypeError("'<' not supported between instances of 'memoryview' and 'memoryview'")

root@odin:~# ls -l /usr/bin/python
lrwxrwxrwx 1 root root 7 Mar  4  2019 /usr/bin/python -> python2
```

3. I will try this morning (Europe/Paris), the latest development edition.

**Comment by olivier-lz** [comment]
I just change the title and description, because it's mistake, the 4.4 package is ok, I just do not correctly understand how Github release works...

**Comment by iredmail** [comment]
I believe the latest development edition fixed this issue. :)

**Comment by olivier-lz** [comment]
Everythings works fine, with python3 and the lastest dev. :smiley:
Thank you.

**Comment by iredmail** [comment]
Thanks for the feedback. :)
