### ISSUE TITLE
SRS does not rewrite addresses containing "/" and other permitted characters

### ISSUE THREAD

**Issue by gregkster** [iredmail/iRedAPD#7]
Addresses like the following don't get rewritten.  Here's a sample telnet conversation with the iredapd on the SRS port:

get Aee9Jz5ViQMS/ZuI48++OfQ==_1107588344726_8j8pIBXOEeW369SuUoQ9KA==@in.constantcontact.com

500 Not a valid email address, bypassed.

get Aee9Jz5ViQMSZuI48++OfQ==_1107588344726_8j8pIBXOEeW369SuUoQ9KA==@in.constantcontact.com

200 SRS0=/inf=JK=in.constantcontact.com=Aee9Jz5ViQMSZuI48++OfQ==_1107588344726_8j8pIBXOEeW369SuUoQ9KA==@mydomain.com

Note that if I remove the "/" character, it does work, and the output contains a "/" character.

Looking at the code, I see the function is_email(s) contains the following line:
if not set(s) & set(r'~!$%^*()\/ ') and regxes.cmp_email.match(s):

So looks like any email containing a character in that set above is going to trigger a "500 Not a valid email address, bypassed."

The wikipedia article https://en.wikipedia.org/wiki/Email_address  states that printable characters including !#$%&'*+-/=?^_`{|}~ are allowed.  Even more stuff is allowed when quoted.

The rfc is little bit tougher to parse, but it looks like only back slash and quote character are prohibited.

https://tools.ietf.org/html/rfc5322#section-3.2.4
   qtext           =   %d33 /             ; Printable US-ASCII
                       %d35-91 /          ;  characters not including
                       %d93-126 /         ;  "\" or the quote character
                       obs-qtext

**Comment by iredmail** [comment]
Would you like to send a PR to fix this issue? :)
